#!/bin/bash

if [ "$(uname)" == "Darwin" ]; then
    # Mac OS X
    
    # Otherwise we gonna have "The requested image's platform (linux/amd64) does not match the detected host platform..." on Apple Silicon
    export DOCKER_DEFAULT_PLATFORM=linux/amd64
    docker run -i -t ubercadence/cli:master --address host.docker.internal:7933 --transport tchannel "$@"
  else
    # Linux
    docker run -i -t --network=host ubercadence/cli:master --address 127.0.0.1:7933 --transport tchannel "$@"
fi
